services:
  db:
    image: postgres:16
    container_name: tracenet_db
    restart: always
    environment:
      POSTGRES_USER: tracenet
      POSTGRES_PASSWORD: tracenet_dev_password
      POSTGRES_DB: tracenet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
